import Foundation

enum AppConstantsStorage {
    static let themeKey = "AppTheme"
    static let fontSizeKey = "FontSize"
    static let fontFamilyKey = "FontFamily"
    static let indentationStyleKey = "IndentationStyle"
    static let lastWorkspacePathKey = "LastWorkspacePath"
    static let showLineNumbersKey = "ShowLineNumbers"
    static let wordWrapKey = "WordWrap"
    static let minimapVisibleKey = "MinimapVisible"
    static let sidebarWidthKey = "SidebarWidth"
    static let terminalHeightKey = "TerminalHeight"
    static let chatPanelWidthKey = "ChatPanelWidth"
    static let cliTimeoutSecondsKey = "Agent.CliTimeoutSeconds"
    static let agentMemoryEnabledKey = "Agent.MemoryEnabled"
    static let agentQAReviewEnabledKey = "Agent.QAReviewEnabled"
    static let inlineCompletionEnabledKey = "Editor.InlineCompletion.Enabled"
    static let inlineCompletionDebounceMsKey = "Editor.InlineCompletion.DebounceMs"
    static let inlineCompletionAggressivenessKey = "Editor.InlineCompletion.Aggressiveness"
    static let inlineCompletionMaxLengthKey = "Editor.InlineCompletion.MaxLength"
    static let inlineCompletionMultilineEnabledKey = "Editor.InlineCompletion.MultilineEnabled"
    static let inlineCompletionRetrievalEnabledKey = "Editor.InlineCompletion.RetrievalEnabled"
    static let inlineCompletionRoutingModeKey = "Editor.InlineCompletion.RoutingMode"
    static let inlineCompletionDebugOverlayKey = "Editor.InlineCompletion.DebugOverlay"
    static let codebaseIndexEnabledKey = "CodebaseIndexEnabled"
    static let codebaseIndexAIEnrichmentEnabledKey = "CodebaseIndexAIEnrichmentEnabled"
    static let enabledLanguageModulesKey = "EnabledLanguageModules"
    static let disabledLanguageModuleCapabilitiesKey = "DisabledLanguageModuleCapabilities"
}
