import Foundation

enum AppConstantsStorage {
    static let themeKey = "AppTheme"
    static let fontSizeKey = "FontSize"
    static let fontFamilyKey = "FontFamily"
    static let indentationStyleKey = "IndentationStyle"
    static let lastWorkspacePathKey = "LastWorkspacePath"
    static let showLineNumbersKey = "ShowLineNumbers"
    static let wordWrapKey = "WordWrap"
    static let minimapVisibleKey = "MinimapVisible"
    static let sidebarWidthKey = "SidebarWidth"
    static let terminalHeightKey = "TerminalHeight"
    static let chatPanelWidthKey = "ChatPanelWidth"
    static let cliTimeoutSecondsKey = "Agent.CliTimeoutSeconds"
    static let agentMemoryEnabledKey = "Agent.MemoryEnabled"
    static let aiProviderKey = "AI.Provider"
    static let localModelEnabledKey = "AI.LocalModel.Enabled"
    static let localModelSelectedModelIdKey = "AI.LocalModel.SelectedModelId"
    static let localModelQuantizationKey = "AI.LocalModel.Quantization"
    static let localModelAllowRemoteFallbackKey = "AI.LocalModel.AllowRemoteFallback"
    static let localModelContextBudgetTokensKey = "AI.LocalModel.ContextBudgetTokens"
    static let localModelMaxOutputTokensKey = "AI.LocalModel.MaxOutputTokens"
    static let localModelMaxAnswerTokensKey = "AI.LocalModel.MaxAnswerTokens"
    static let localModelMaxReasoningTokensKey = "AI.LocalModel.MaxReasoningTokens"
    static let localModelManifestURLKey = "AI.LocalModel.ManifestURL"
    static let codebaseIndexEnabledKey = "CodebaseIndexEnabled"
    static let codebaseIndexAIEnrichmentEnabledKey = "CodebaseIndexAIEnrichmentEnabled"
    static let enabledLanguageModulesKey = "EnabledLanguageModules"
}
